---
  - name: Base OS packages
    apt: name={{ item }} state=present
    with_items:
     - git 
     - python-software-properties
     - python
     - g++
     - make
     - libpq-dev
     - postgresql
     - postgresql-client
     - python-psycopg2

