---
  - name: Base OS packages
    apt: name={{ item }} state=present
    with_items:
     - git 
     - python-software-properties
     - python
     - g++
     - make
     - python-psycopg2

  - name: Node.js | Add the node.js PPA
    apt_repository: repo=ppa:chris-lea/node.js

  - name: Node.js | Install nodejs and npm
    apt: pkg=nodejs update_cache=yes

