---
- name: Download the api source from github
  git: repo=https://github.com/ripple/rippled-peers-api
       dest=/opt/rippled-peers-api
       force=yes

- name: Grant ownership of application to deploy user
  file: path=/opt/rippled-peers-api owner={{deploy_user}}

- name: Install node.js dependencies with npm
  npm: path=/opt/rippled-peers-api state=latest

- name: Copy the nginx config for anpay in place
  template: src=upstart.conf.j2 dest=/etc/init/rippled-peers-api.conf mode=644 owner=root group=root

- name: Start api service
  service: name=rippled-peers-api state=started

