---
- name: Install nginx
  apt: name=nginx state=present

- name: Copy the nginx config for anpay in place
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/rippled-peers-api.conf mode=644 owner=root group=root

- name: Configure nginx files
  file: src=/etc/nginx/sites-available/rippled-peers-api.conf dest=/etc/nginx/sites-enabled/rippled-peers-api.conf state=link
  sudo: yes 
- file: path=/etc/nginx/sites-enabled/default state=absent
  sudo: yes 
- file: path=/etc/nginx/sites-available/default state=absent
  sudo: yes 

- name: SSL directory
  file: path=/etc/ssl/certs/rippled-peers-api owner=root group=root mode=740 state=directory

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=California/L=SanFrancisco/O=Engineering/CN=api-staging.peers.ripple.com" -days 3650 -keyout /etc/ssl/certs/rippled-peers-api/server.key -out /etc/ssl/certs/rippled-peers-api/server.crt -extensions v3_ca creates=/etc/ssl/certs/rippled-peers-api/server.crt

- name: restart nginx
  service: name=nginx state=restarted
